
export const GET_F1SEASONS_DATA = "GET_F1SEASONS_DATA";
export const GET_F1SEASONS_SUCCEEDED = "GET_F1SEASONS_SUCCEEDED";
export const GET_F1SEASONS_FAILED = "GET_F1SEASONS_FAILED";

export const GET_RACEWINNERS_DATA = "GET_RACEWINNERS_DATA";
export const GET_RACEWINNERS_SUCCEEDED = "GET_RACEWINNERS_SUCCEEDED";
export const GET_RACEWINNERS_FAILED = "GET_RACEWINNERS_FAILED";